Name:           ros-kinetic-rosflight
Version:        1.0.0
Release:        1%{?dist}
Summary:        ROS rosflight package

Group:          Development/Libraries
License:        BSD
URL:            http://rosflight.org
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       eigen3-devel
Requires:       ros-kinetic-eigen-stl-containers
Requires:       ros-kinetic-geometry-msgs
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-rosflight-msgs
Requires:       ros-kinetic-sensor-msgs
Requires:       ros-kinetic-std-msgs
Requires:       ros-kinetic-std-srvs
Requires:       ros-kinetic-tf
Requires:       yaml-cpp-devel
BuildRequires:  boost-devel
BuildRequires:  eigen3-devel
BuildRequires:  git
BuildRequires:  pkgconfig
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-eigen-stl-containers
BuildRequires:  ros-kinetic-geometry-msgs
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-rosflight-msgs
BuildRequires:  ros-kinetic-sensor-msgs
BuildRequires:  ros-kinetic-std-msgs
BuildRequires:  ros-kinetic-std-srvs
BuildRequires:  ros-kinetic-tf
BuildRequires:  yaml-cpp-devel

%description
Package for interfacing to the ROSflight autopilot firmware over MAVLink

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed Mar 14 2018 Daniel Koch <daniel.p.koch@gmail.com> - 1.0.0-1
- Autogenerated by Bloom

* Tue Mar 13 2018 Daniel Koch <daniel.p.koch@gmail.com> - 1.0.0-0
- Autogenerated by Bloom

* Fri Jun 02 2017 Daniel Koch <daniel.p.koch@gmail.com> - 0.1.3-0
- Autogenerated by Bloom

* Wed May 24 2017 Daniel Koch <daniel.koch@byu.edu> - 0.1.2-0
- Autogenerated by Bloom

* Wed May 24 2017 Daniel Koch <daniel.koch@byu.edu> - 0.1.1-0
- Autogenerated by Bloom

* Tue May 23 2017 Daniel Koch <daniel.koch@byu.edu> - 0.1.0-1
- Autogenerated by Bloom

* Tue May 23 2017 Daniel Koch <daniel.koch@byu.edu> - 0.1.0-0
- Autogenerated by Bloom

