Name:           ros-kinetic-rosflight-utils
Version:        0.1.2
Release:        0%{?dist}
Summary:        ROS rosflight_utils package

Group:          Development/Libraries
License:        TODO
URL:            http://rosflight.org
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-gazebo-msgs
Requires:       ros-kinetic-geometry-msgs
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-rosflight-msgs
Requires:       ros-kinetic-rosgraph-msgs
Requires:       ros-kinetic-rospy
Requires:       ros-kinetic-sensor-msgs
Requires:       ros-kinetic-std-srvs
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-gazebo-msgs
BuildRequires:  ros-kinetic-geometry-msgs
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-rosflight-msgs
BuildRequires:  ros-kinetic-rosgraph-msgs
BuildRequires:  ros-kinetic-rospy
BuildRequires:  ros-kinetic-sensor-msgs
BuildRequires:  ros-kinetic-std-srvs

%description
Supporting utilities for ROSflight packages

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed May 24 2017 gary <gary.ellingson@byu.edu> - 0.1.2-0
- Autogenerated by Bloom

* Wed May 24 2017 gary <gary.ellingson@byu.edu> - 0.1.1-0
- Autogenerated by Bloom

* Tue May 23 2017 gary <gary.ellingson@byu.edu> - 0.1.0-1
- Autogenerated by Bloom

* Tue May 23 2017 gary <gary.ellingson@byu.edu> - 0.1.0-0
- Autogenerated by Bloom

