Name:           ros-lunar-rosflight-sim
Version:        1.0.0
Release:        0%{?dist}
Summary:        ROS rosflight_sim package

Group:          Development/Libraries
License:        BSD
URL:            http://rosflight.org
Source0:        %{name}-%{version}.tar.gz

Requires:       eigen3-devel
Requires:       gazebo-devel
Requires:       ros-lunar-gazebo-plugins
Requires:       ros-lunar-gazebo-ros
Requires:       ros-lunar-geometry-msgs
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-rosflight-firmware
Requires:       ros-lunar-rosflight-msgs
BuildRequires:  eigen3-devel
BuildRequires:  gazebo-devel
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-gazebo-plugins
BuildRequires:  ros-lunar-gazebo-ros
BuildRequires:  ros-lunar-geometry-msgs
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-rosflight-firmware
BuildRequires:  ros-lunar-rosflight-msgs

%description
Software-in-the-loop (SIL) simulator for the ROSflight firmware

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Thu Mar 15 2018 James Jackson <superjax08@gmail.com> - 1.0.0-0
- Autogenerated by Bloom

