Name:           ros-kinetic-rosflight-pkgs
Version:        1.0.0
Release:        1%{?dist}
Summary:        ROS rosflight_pkgs package

Group:          Development/Libraries
License:        BSD
URL:            http://rosflight.org
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-kinetic-rosflight
Requires:       ros-kinetic-rosflight-firmware
Requires:       ros-kinetic-rosflight-msgs
Requires:       ros-kinetic-rosflight-sim
Requires:       ros-kinetic-rosflight-utils
BuildRequires:  ros-kinetic-catkin

%description
ROS interface for the ROSflight autpilot stack

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed Mar 14 2018 Daniel Koch <daniel.p.koch@gmail.com> - 1.0.0-1
- Autogenerated by Bloom

* Tue Mar 13 2018 Daniel Koch <daniel.p.koch@gmail.com> - 1.0.0-0
- Autogenerated by Bloom

* Fri Jun 02 2017 Daniel Koch <daniel.p.koch@gmail.com> - 0.1.3-0
- Autogenerated by Bloom

* Wed May 24 2017 Daniel Koch <daniel.koch@byu.edu> - 0.1.2-0
- Autogenerated by Bloom

* Wed May 24 2017 Daniel Koch <daniel.koch@byu.edu> - 0.1.1-0
- Autogenerated by Bloom

* Tue May 23 2017 Daniel Koch <daniel.koch@byu.edu> - 0.1.0-1
- Autogenerated by Bloom

* Tue May 23 2017 Daniel Koch <daniel.koch@byu.edu> - 0.1.0-0
- Autogenerated by Bloom

